name: Deploy VitePress Docs

# 触发条件：推送到main分支时执行
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入仓库内容（用于部署GitHub Pages）

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史，确保最后更新时间正确

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.0.1  # 指定Node.js版本
          cache: 'pnpm'         # 缓存pnpm依赖加速构建

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1  # 指定pnpm版本
          run_install: false

      - name: 安装依赖
        run: pnpm install --frozen-lockfile  # 严格按照lockfile安装依赖

      - name: 构建文档
        run: pnpm docs:build  # 执行VitePress构建命令（默认命令，需与package.json一致）

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的GitHub Token
          publish_dir: ./docs/.vitepress/dist        # VitePress构建输出目录
          force_orphan: true                         # 强制创建孤儿分支（减少历史体积）
